#spring.application.name=AccountingCard
spring:
  application:
    name: AccountingCard
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
